### ISSUE TITLE
Change SSL connection properties

### ISSUE THREAD

**Issue by edwinvanelk** [mendix/EmailModuleWithTemplates#14]
Can the module be checked against the tips in:
https://javaee.github.io/javamail/FAQ#commonmistakes

Especially:
Setting various socketFactory properties. Long, long ago JavaMail didn't have built in support for SSL connections, so it was necessary to set these properties to use SSL. This hasn't been the case for years; remove these properties and simplify your code. The easiest way to enable SSL support in current versions of JavaMail is to set the property "mail.smtp.ssl.enable" to "true". (Replace "smtp" with "imap" or "pop3" as appropriate.)

Can the properties used for SSL connection changed from:

properties.setProperty(EmailConstants.MAIL_SMTP_SOCKET_FACTORY_PORT, mail.getSslSmtpPort());
properties.setProperty(EmailConstants.MAIL_SMTP_SOCKET_FACTORY_CLASS, "javax.net.ssl.SSLSocketFactory");

to:

properties.setProperty(EmailConstants.MAIL_SMTP_SSL_ENABLE, "true");
properties.setProperty(EmailConstants.MAIL_PORT, mail.getSslSmtpPort());

**Comment by RoelandSalij** [comment]
Thanks for your feedback!
Are you experiencing any issues as a result of the outdated code?

**Comment by edwinvanelk** [comment]
We ran into some problems using SSL with messages like "Unrecognized SSL message, plaintext connection". During debugging we simplified the code using the quoted suggestions, however the problem has not yet been solved and we changed to TLS instead of using SSL.

Don't think issue is result of outdated code.
