### ISSUE TITLE
Java compile error when having an entity called "Subject" in any other module in same project

### ISSUE THREAD

**Issue by rvhofwegen** [mendix/EmailModuleWithTemplates#28]
Error given on local deployment after download module and having a entity called "Subject"
Error doesn't give clear reason about conflict.
========
Buildfile: ........\Documents\Projects\Test Email shizzle-main\deployment\build_core.xml

compile:
    [javac] Compiling 3 source files to ........\Documents\Projects\Test Email shizzle-main\deployment\run\bin
    [javac] ........\Documents\Projects\Test Email shizzle-main\javasource\emailtemplate\actions\SendEmail.java:159: error: cannot find symbol
    [javac] 			throw new CoreException("Unable to convert the Html body to plain text for email: " + this.Subject + " to: " + this.ToAddresses, e);
    [javac] 			                                                                                          ^
    [javac]   symbol: variable Subject
    [javac] ........\Documents\Projects\Test Email shizzle-main\javasource\emailtemplate\actions\SendEmail.java:163: error: cannot find symbol
    [javac] 			EmailModule.mail(config, this.HtmlBody, this.PlainBody, this.Subject, toList, ccList, bccList, this.getContext(), this.__AttachmentList, headerMap);
    [javac] 			                                                            ^
    [javac]   symbol: variable Subject
    [javac] ........\Documents\Projects\Test Email shizzle-main\javasource\emailtemplate\actions\SendEmail.java:166: error: cannot find symbol
    [javac] 			this._logNode.info("Did not send email '"+this.Subject + "' to '"+ this.ToAddresses + "' since the 'EmailTemplate.SendingEnabled' constant is not enabled."); 
    [javac] 			                                              ^
    [javac]   symbol: variable Subject
    [javac] 3 errors

BUILD FAILED
........\Documents\Projects\Test Email shizzle-main\deployment\build_core.xml:29: Compile failed; see the compiler error output for details.

Total time: 1 second

**Comment by RoelandSalij** [comment]
Hi Rene,
The root cause of this problem is that the parameters for java actions can conflict with entities in the modeler.
Mendix changes the params of the java action in this module in this specific case and that breaks the code in the java action.

What you describe is not a result of this module, but a result of the Mendix modeler.

When your issue is "Error doesn't give clear reason about conflict." the issue should be addressed to the Mendix Modeler.

**Comment by rvhofwegen** [comment]
My issue is that I get an error while downloading and running a Mendix supported module; at least specify it in the documentation as a known issue. Thx
