### ISSUE TITLE
Issue adding 10.2.3 in Studio Pro

### ISSUE THREAD

**Issue by wpgrant** [mendix/EmailModuleWithTemplates#33]
The error says: Package '.....tzpmff2s.yka' is not a module package, but a project package.

**Comment by wpgrant** [comment]
- Tested in Studio Pro 8.7
- Prior versions work

**Comment by RoelandSalij** [comment]
This issue was resolved last week. There was an issue in App Store relating to a file being retrieved from cache. Please let us know when you still encounter problems.
